name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup go
        uses: actions/setup-go@v5

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install run-all
        run: npm i npm-run-all --save-dev

      - name: Build frontend
        run: npm run build

      - name: Build backend
        run: go build -o doit ./cmd
